"""Initial Migration

Revision ID: e6d48be4ff71
Revises: 346c4ef1948a
Create Date: 2020-12-07 16:03:21.963473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d48be4ff71'
down_revision = '346c4ef1948a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phonenumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phonenumber', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
